// import React from 'react'
// import Product_card from './Card/Product_card'
// const productData = [
//   {
//     id: 1,
//     image: "/image/drink.png",
//     discountText: "$15 off",
//     name: "Nestle Ice Coffee",
//     price: "$37",
//     originalPrice: "$52",
//     weight: "500g Pouch",
//     description:
//       "Super smooth and creamy vanilla half and half crowned with s...",
//     promotion: "Valid until 2024, Sept 19",
//     promotedBy: "Lingo Pvt LTD.",
//     others: "+3 others",
//   },
//   {
//     id: 2,
//     image: "/image/drink.png",
//     discountText: "$16 off",
//     name: "Nestle Ice Coffee",
//     price: "$37",
//     originalPrice: "$52",
//     weight: "500g Pouch",
//     description:
//       "Super smooth and creamy vanilla half and half crowned with s...",
//     promotion: "Valid until 2024, Sept 19",
//     promotedBy: "Lingo Pvt LTD.",
//     others: "+3 others",
//   },
//   {
//     id: 3,
//     image: "/image/drink.png",
//     discountText: "$15 off",
//     name: "Nestle Ice Coffee",
//     price: "$37",
//     originalPrice: "$52",
//     weight: "500g Pouch",
//     description:
//       "Super smooth and creamy vanilla half and half crowned with s...",
//     promotion: "Valid until 2024, Sept 19",
//     promotedBy: "Lingo Pvt LTD.",
//     others: "+3 others",
//   },
//   {
//     id: 4,
//     image: "/image/drink.png",
//     discountText: "$15 off",
//     name: "Nestle Ice Coffee",
//     price: "$37",
//     originalPrice: "$52",
//     weight: "500g Pouch",
//     description:
//       "Super smooth and creamy vanilla half and half crowned with s...",
//     promotion: "Valid until 2024, Sept 19",
//     promotedBy: "Lingo Pvt LTD.",
//     others: "+3 others",
//   },
//   {
//     id: 5,
//     image: "/image/drink.png",
//     discountText: "$15 off",
//     name: "Nestle Ice Coffee",
//     price: "$37",
//     originalPrice: "$52",
//     weight: "500g Pouch",
//     description:
//       "Super smooth and creamy vanilla half and half crowned with s...",
//     promotion: "Valid until 2024, Sept 19",
//     promotedBy: "Lingo Pvt LTD.",
//     others: "+3 others",
//   },
//   {
//     id: 6,
//     image: "/image/drink.png",
//     discountText: "$15 off",
//     name: "Nestle Ice Coffee",
//     price: "$37",
//     originalPrice: "$52",
//     weight: "500g Pouch",
//     description:
//       "Super smooth and creamy vanilla half and half crowned with s...",
//     promotion: "Valid until 2024, Sept 19",
//     promotedBy: "Lingo Pvt LTD.",
//     others: "+3 others",
//   },
//   {
//     id: 7,
//     image: "/image/drink.png",
//     discountText: "$15 off",
//     name: "Nestle Ice Coffee",
//     price: "$37",
//     originalPrice: "$52",
//     weight: "500g Pouch",
//     description:
//       "Super smooth and creamy vanilla half and half crowned with s...",
//     promotion: "Valid until 2024, Sept 19",
//     promotedBy: "Lingo Pvt LTD.",
//     others: "+3 others",
//   },
//   {
//     id: 8,
//     image: "/image/drink.png",
//     discountText: "$15 off",
//     name: "Nestle Ice Coffee",
//     price: "$37",
//     originalPrice: "$52",
//     weight: "500g Pouch",
//     description:
//       "Super smooth and creamy vanilla half and half crowned with s...",
//     promotion: "Valid until 2024, Sept 19",
//     promotedBy: "Lingo Pvt LTD.",
//     others: "+3 others",
//   },
//   {
//     id: 9,
//     image: "/image/drink.png",
//     discountText: "$15 off",
//     name: "Nestle Ice Coffee",
//     price: "$37",
//     originalPrice: "$52",
//     weight: "500g Pouch",
//     description:
//       "Super smooth and creamy vanilla half and half crowned with s...",
//     promotion: "Valid until 2024, Sept 19",
//     promotedBy: "Lingo Pvt LTD.",
//     others: "+3 others",
//   },
//   {
//     id: 10,
//     image: "/image/drink.png",
//     discountText: "$15 off",
//     name: "Nestle Ice Coffee",
//     price: "$37",
//     originalPrice: "$52",
//     weight: "500g Pouch",
//     description:
//       "Super smooth and creamy vanilla half and half crowned with s...",
//     promotion: "Valid until 2024, Sept 19",
//     promotedBy: "Lingo Pvt LTD.",
//     others: "+3 others",
//   },
//   {
//     id: 11,
//     image: "/image/drink.png",
//     discountText: "$15 off",
//     name: "Nestle Ice Coffee",
//     price: "$37",
//     originalPrice: "$52",
//     weight: "500g Pouch",
//     description:
//       "Super smooth and creamy vanilla half and half crowned with s...",
//     promotion: "Valid until 2024, Sept 19",
//     promotedBy: "Lingo Pvt LTD.",
//     others: "+3 others",
//   },
//   {
//     id: 12,
//     image: "/image/drink.png",
//     discountText: "$15 off",
//     name: "Nestle Ice Coffee",
//     price: "$37",
//     originalPrice: "$52",
//     weight: "500g Pouch",
//     description:
//       "Super smooth and creamy vanilla half and half crowned with s...",
//     promotion: "Valid until 2024, Sept 19",
//     promotedBy: "Lingo Pvt LTD.",
//     others: "+3 others",
//   },
//   {
//     id: 13,
//     image: "/image/drink.png",
//     discountText: "$15 off",
//     name: "Nestle Ice Coffee",
//     price: "$37",
//     originalPrice: "$52",
//     weight: "500g Pouch",
//     description:
//       "Super smooth and creamy vanilla half and half crowned with s...",
//     promotion: "Valid until 2024, Sept 19",
//     promotedBy: "Lingo Pvt LTD.",
//     others: "+3 others",
//   },
//   {
//     id: 14,
//     image: "/image/drink.png",
//     discountText: "$15 off",
//     name: "Nestle Ice Coffee",
//     price: "$37",
//     originalPrice: "$52",
//     weight: "500g Pouch",
//     description:
//       "Super smooth and creamy vanilla half and half crowned with s...",
//     promotion: "Valid until 2024, Sept 19",
//     promotedBy: "Lingo Pvt LTD.",
//     others: "+3 others",
//   },
//   {
//     id: 15,
//     image: "/image/drink.png",
//     discountText: "$15 off",
//     name: "Nestle Ice Coffee",
//     price: "$37",
//     originalPrice: "$52",
//     weight: "500g Pouch",
//     description:
//       "Super smooth and creamy vanilla half and half crowned with s...",
//     promotion: "Valid until 2024, Sept 19",
//     promotedBy: "Lingo Pvt LTD.",
//     others: "+3 others",
//   },
// ];

// const TopSkuCard = () => {
//   return <Product_card data={productData} />;
// }

// export default TopSkuCard